import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import PageLoadEffects from "@/components/PageLoadEffects";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "PAPE Dimitri - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        <Navbar />
        <PageLoadEffects />
        <main> {children} </main>
        <Footer />
      </body>
    </html>

  );
}
