import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import PageLoadEffects from "@/components/PageLoadEffects";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        <Navbar />
        <PageLoadEffects />
        <main> {children} </main>
      </body>
    </html>
  );
}
